<div class="card">

  <div class="card-body">

    <h1>Gizlilik Politikamız</h1>

    <br>

  <p>Tüketici/kullanıcılarımızın www.kolekty.com sitemize vermiş olduğu bilgilerin gizliliği, korunması ve ilgili diğer hususlarda aşağıda cari kuralları belirtilen Gizlilik Politikası benimsenmiştir.</p>
  <p>Kolekty üye hizmet verenlerinden ve talep formu dolduran tüketiciye/kullanıcıya daha iyi hizmet sağlayabilmek amacıyla çeşitli (e-posta, telefon, isim, adres vb.) bilgileri vermesini talep eder.</p>
  <p>kolekty.com adına hizmet sağlayan, hizmet sağlayıcılar; Üye/kullanıcı/tüketici/hizmet veren ustalara internet sitemiz üzerinden hizmet, ürün, promosyon gibi çeşitli fırsatlar sunabilmek için özenle seçtiğimiz veya seçeceğimiz çözüm ortağımız şirketler. Ve Yasal yükümlülükleri yerine getirmek, hileleri önlemek ve kullanıcılarımızın güvenliklerini korumak gibi özel durumlarda diğer 3. parti kurumlar ve yasal merciler. Yukarıda belirtilen bütün durumlarda ve çeşitli reklam mecralarında toplu, kişisel olmayan bilgileri paylaşabiliriz.</p>
  <p>kolekty.com’a üye olan kişi, yürürlükte bulunan ve/veya yürürlüğe alınacak uygulamalar kapsamında kolekty.com tarafından kendisine ürün ve hizmet tanıtımları, reklamlar, kampanyalar, avantajlar, anketler ve diğer müşteri memnuniyeti uygulamaları sunulmasına izin verdiğini beyan ve kabul eder. Üye, kolekty.com’a üye olurken ve/veya başka yollarla geçmişte vermiş olduğu ve/veya gelecekte vereceği kişisel ve alışveriş bilgilerinin ve alışveriş ve/veya tüketici davranış bilgilerinin yukarıdaki amaçlarla toplanmasına, kolekty.com iştiraki olan tüm şirketler ile paylaşılmasına, kolekty.com iştiraki olan tüm şirketler tarafından kullanılmasına ve arşivlenmesine izin verdiğini beyan ve kabul eder. Üye aksini bildirmediği sürece üyeliği sona erdiğinde de verilerin toplanmasına, kolekty.com iştiraki olan tüm şirketler ile paylaşılmasına, kolekty.com iştiraki olan tüm şirketler tarafından kullanılmasına ve arşivlenmesine izin verdiğini beyan ve kabul eder. Üye aksini bildirmediği sürece www.kolekty.com iştiraki olan tüm şirketlerin kendisi ile internet, telefon, SMS, vb. iletişim kanalları kullanarak irtibata geçmesine izin verdiğini beyan ve kabul eder. Üye yukarıda bahsi geçen bilgilerin toplanması, paylaşılması, kullanılması, arşivlenmesi ve kendisine erişilmesi nedeniyle doğrudan ve/veya dolaylı maddi ve/veya manevi menfi ve/veya müsbet, velhasıl herhangi bir zarara uğradığı konusunda talepte bulunmayacağını ve kolekty.com iştiraki olan şirketleri sorumlu tutmayacağını beyan ve kabul eder. Üye veri paylaşım tercihlerini değiştirmek isterse, bu talebini kolekty.com’un çağrı merkezlerine iletebilir.</p>
  <p>www.kolekty.com, üyenin kişisel bilgilerini yasal bir zorunluluk olarak istendiğinde veya <br mx-5>
    <div class="mx-5">Yasal gereklere uygun hareket etmek veya www.kolekty.com’a tebliğ edilen yasal işlemlere uymak<br></div>     
    <div class="mx-5">Kolekty ve www.kolekty.com web sitesi ailesinin haklarını ve mülkiyetini korumak ve savunmak<br></div>     
    <div class="mx-5">için gerekli olduğuna iyi niyetle kanaat getirdiği hallerde açıklayabilir.</div>     
  </p>
  <p>www.kolekty.com web sitesinin virus ve benzeri amaçlı yazılımlardan arındırılmış olması için mevcut imkanlar dahilinde tedbir alınmıştır. Bunun yanında nihai güvenliğin sağlanması için kullanıcının, kendi virus koruma sistemini tedarik etmesi ve gerekli korunmayı sağlaması gerekmektedir. Bu bağlamda üye kolekty.com web sitesi\'ne girmesiyle, kendi yazılım ve işletim sistemlerinde oluşabilecek tüm hata ve bunların doğrudan yada dolaylı sonuçlarından kendisinin sorumlu olduğunu kabul etmiş sayılır.</p>
  <p>Sitemizi ziyaret için herhangi bir kişisel bilginizi bize vermek zorunda değilsiniz. Ancak, hizmetlerimizden faydalanmak için üye olmanız ve bazı kişisel bilgilerinizi vermeniz gerekmektedir.</p>
  <p>www.kolekty.com otomatik olarak, ip adresinizi, tarayıcı tipiniz veya tarayıcı dilinizi, ziyaretinizin tarih ve saatini saklar ve bu bilgileri kullanıcılarımızın istek, tercihlerini ve kullanıcı trendlerini belirlemek için kullanır.</p>
  <p>kolekty.com sitesinde çeşitli reklam firmalarının ve veya reklam ağlarının reklam görüntülemelerine izin verebilir. Eğer sitemizde kişisel bilgilerinizi bir şekilde kendiniz yayınlarsanız, bu yayınladığınız bilgileri kimlerin okuyacağını ve bu bilgiler ile neler yapacaklarını kontrol edemeyiz. Bu nedenle sitemizde kişisel bilgi yayınlarken dikkatli olmanızı öneririz.Aksi takdirde olanlardan kolekty.com sorumlu değildir.</p>
  <p>www.kolekty.com olarak tüketici/kullanıcıdan sağlamış olduğumuz bilgileri <br>
    <div class="mx-5">Hizmet veya ürün talebinizi karşılamak <br></div> 
    <div class="mx-5"> İlginizi çekebilecek hizmet veya ürünleri sunmak<br></div> 
    <div class="mx-5"> İnternet sitemizde görüntülediğiniz içerik ve reklamları kişiselleştirmek <br></div> 
    <div class="mx-5"> İnternet sitemizin kullanımını kolaylaştırmak<br></div> 
    <div class="mx-5"> Hesap ve tercihlerinizi yönetmek<br></div> 
    <div class="mx-5"> Sitemizin kullanımını analiz etmek, sağladığı hizmet ve ürünleri geliştirmek<br></div> 
    <div class="mx-5"> Hileli işlemleri tanımlamak ve sitemizi bu gibi tehlikelere karşı korumak<br></div> 
    <div class="mx-5"> Sitemizin kullanım koşullarını infaz etmek için kullanabiliriz.<br></div> 
  </p>
  <p>Gizlilik politikamızı kolekty.com’da gerçekleşen değişikliklere uygun olarak sık sık değiştirebiliriz. Eğer bilgi toplama yöntemlerimiz ve bu bilgileri kullanma şekillerimiz açısından köklü değişiklikler yapmak zorunda kalırsak bu durumu size bize vermiş e-posta adresine e-posta göndererek veya sitemizde yayınlayarak bildirimde bulunuruz.E-posta bildirimine 7 gün içinde yanıt verilmemesi ya da siteye ilk girişte değişiklik yapılan gizlilik bildiriminin onaylanmaması halinde kolekty.com üyenin siteyi kullanım hakkını kapatabilir ve siteden üyeyi silebilir.</p>
  <p>Sitemizin diğer internet-web sitelerine bağlantı verdiği hallerde tüm kullanım ve işlemler için o sitelere ait gizlilik-güvenlik politikası ve kullanım şartları geçerlidir; Sitemizden reklam, banner, içerik görmek veya başka herhangi bir amaç ile ulaşılan diğer web sitelerinden bilgi kullanımları, keza sitelerin etik ilkeleri, gizlilik-güvenlik prensipleri, servis kalitesi ve diğer uygulamaları sebebi ile oluşabilecek ihtilaf, maddi-manevi zarar ve kayıplardan Kolekty sorumlu değildir.</p>
  <p>Kolekty, kullanıcılara ve kullanıcıların www.kolekty.com sitesinin kullanımına dair bilgileri, teknik bir iletişim dosyasını (Kurabiye-Cookie) kullanarak elde edebilir. Ancak, kullanıcılar dilerlerse teknik iletişim dosyasının gelmemesi veya teknik iletişim dosyası gönderildiğinde ikaz verilmesini sağlayacak biçimde tarayıcı ayarlarını değiştirebilirler. Ancak, bu şekilde elde ettiğimiz bilgiler size vereceğimiz hizmetin daha çabuk ve kaliteli olmasında kullanılacağından, bu özelliği açık bırakmanızı öneririz.</p>
  <p>Bu sayfada yer alan güvenlik bilgileri kolekty.com tarafından güncellenebilir.Lütfen bu bilgileri periyodik olarak kontrol ediniz.</p>
  <p>Sunucu kayıtlarımız otomatik olarak, ip adresinizi, tarayıcı tipiniz veya tarayıcı dilinizi, ziyaretinizin tarih ve saatini saklar ve bu bilgileri kullanıcılarımızın istek, tercihlerini ve kullanıcı trendlerini belirlemek için kullanır. İnternet sitemizdeki kişisel deneyiminizin kalitesini arttırmak için bilgisayarınıza bir veya birden fazla bilgi toplayıcı çerezler atayabiliriz.Sitemizin kullanımını ölçmek amaçlı çeşitli standart internet araçları kullanıp, hizmet ve reklamlarımızı bu bilgiler ışığında yeniden uyarlayabiliriz.</p>
  <p>www.kolekty.com’da çeşitli reklam firmalarının ve veya reklam ağlarının reklam görüntülemelerine izin verebiliriz.</p>
  <p>Bu şirketlerle hiç bir şekilde kişisel bilgilerinizi paylaşmayız.Bu şirketler, çerezler gibi çeşitli izleme araçları kullanarak reklamlarıyla etkileşime geçen bilgisayarlardan bilgi toplayabilir.Eğer sitemizde kişisel bilgilerinizi bir şekilde kendiniz yayınlarsanız, bu yayınladığınız bilgileri kimlerin okuyacağını ve bu bilgiler ile neler yapacaklarını kontrol edemeyiz. Bu nedenle sitemizde kişisel bilgi yayınlarken dikkatli olmanızı öneririz.</p>
  <p>Bizim adımıza hizmet sağlayan, kredi kartı ödeme işleyicileri gibi hizmet sağlayıcılar; size internet sitemiz üzerinden hizmet, ürün, promosyon gibi çeşitli fırsatlar sunabilmek için özenle seçtiğimiz veya seçeceğimiz çözüm ortağımız şirketler ve yasal yükümlülükleri yerine getirmek, hileleri önlemek ve kullanıcılarımızın güvenliklerini korumak gibi özel durumlarda diğer 3. parti kurumlar yukarıda belirtilen bütün durumlarda ve çeşitli reklam mecralarında toplu, kişisel olmayan bilgilerinizi bunlarla paylaşabiliriz.</p>
  <p>Kişisel bilgilerinizi bizimle paylaşmamayı tercih edebilirsiniz. Bu durum sitemizin sağladığı çeşitli hizmet ve özelliklere ulaşmanızı engelleyebilir. Tüketici kullanıcılarımız üye hesaplarına girerek promosyonel e-posta ve bültenlerin kendilerine ulaşmasını durdurabilir.İnternet tarayıcınızın ayarlarını değiştirerek çerezleri engelleyebilir veya silebilirsiniz. Bu durum sitemizin sağladığı çeşitli hizmet ve özelliklere ulaşmanızı engelleyebilir. Sistemimizde üyeliğiniz bulunuyorsa hesabınıza giriş yaparak, üyeliğiniz bulunmuyorsa iletişim bilgilerimizde bulunan e-posta adresine posta göndererek kişisel bilgilerinizi görüntüleyebilir veya güncelleyebilir veya üyelikten çıkabilirsiniz.Güvenlik, kişisel bilgilerinizin ortaya çıkmasını, başkalaşmasını, yetki dışında ulaşılmasını önlemek için gerekli olan fiziksel, elektronik ve diğer güvenlik önlemlerini alıyoruz.</p>
  </div>

</div>

